s1=set(input("Enter fruits in set 1"))
s2=set(input("Enter fruits in set 2"))
print(s1.intersection(s2))
print(s1.difference(s2))
print("Count of set 1 :", len(s1)-1)
print("Count of set 2 :", len(s2)-1)
